-- Script de création de la base de données Scolix (PostgreSQL)
-- Structure des 31 tables métier, générée avec pg_dump (--schema-only)

--
-- PostgreSQL database dump
--


-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1




--
-- Name: ai_bias_detection_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_bias_detection_results (
    id uuid NOT NULL,
    semester_id uuid,
    results jsonb NOT NULL,
    computed_at timestamp with time zone NOT NULL
);


--
-- Name: ai_clustering_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_clustering_results (
    id uuid NOT NULL,
    semester_id uuid,
    k smallint NOT NULL,
    clusters jsonb NOT NULL,
    computed_at timestamp with time zone NOT NULL,
    CONSTRAINT ai_clustering_results_k_check CHECK ((k >= 0))
);


--
-- Name: ai_evaluator_bias_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_evaluator_bias_config (
    id bigint NOT NULL,
    normalization_enabled boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: ai_evaluator_bias_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_evaluator_bias_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_evaluator_bias_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_evaluator_bias_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_evaluator_bias_results (
    id uuid NOT NULL,
    semester_id uuid,
    results jsonb NOT NULL,
    computed_at timestamp with time zone NOT NULL
);


--
-- Name: ai_teacher_score_predictions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_teacher_score_predictions (
    id uuid NOT NULL,
    predicted_score numeric(5,2),
    slope numeric(8,4),
    r_squared numeric(5,4),
    data_points smallint NOT NULL,
    details jsonb NOT NULL,
    computed_at timestamp with time zone NOT NULL,
    teacher_id uuid NOT NULL,
    CONSTRAINT ai_teacher_score_predictions_data_points_check CHECK ((data_points >= 0))
);


--
-- Name: ai_training_catalog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_training_catalog (
    id uuid NOT NULL,
    title character varying(200) NOT NULL,
    description text,
    category character varying(20) NOT NULL,
    provider character varying(20) NOT NULL,
    url character varying(200),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: analytics_classification_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.analytics_classification_config (
    id bigint NOT NULL,
    exceptional_threshold numeric(5,2) NOT NULL,
    progression_threshold numeric(5,2) NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: analytics_classification_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.analytics_classification_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analytics_classification_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance_alerts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance_alerts (
    id uuid NOT NULL,
    alert_type character varying(30) NOT NULL,
    status character varying(20) NOT NULL,
    period character varying(10) NOT NULL,
    count integer NOT NULL,
    message text,
    created_at timestamp with time zone NOT NULL,
    resolved_at timestamp with time zone,
    teacher_id uuid NOT NULL,
    CONSTRAINT attendance_alerts_count_check CHECK ((count >= 0))
);


--
-- Name: attendance_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance_records (
    id uuid NOT NULL,
    scheduled_at timestamp with time zone NOT NULL,
    actual_at timestamp with time zone,
    status character varying(20) NOT NULL,
    delay_minutes integer NOT NULL,
    justification text,
    is_justified boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    teacher_id uuid NOT NULL,
    course_id uuid NOT NULL,
    CONSTRAINT attendance_records_delay_minutes_check CHECK ((delay_minutes >= 0))
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id uuid NOT NULL,
    action character varying(20) NOT NULL,
    resource character varying(100) NOT NULL,
    resource_id character varying(100),
    detail text,
    ip_address inet,
    user_agent text,
    "timestamp" timestamp with time zone NOT NULL,
    user_id uuid
);


--
-- Name: auth_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_users (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    id uuid NOT NULL,
    email character varying(254) NOT NULL,
    role character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    is_verified boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    student_profile_id uuid,
    teacher_profile_id uuid
);


--
-- Name: campaigns_evaluation_campaigns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campaigns_evaluation_campaigns (
    id uuid NOT NULL,
    title character varying(180) NOT NULL,
    description text,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id uuid NOT NULL,
    semester_id uuid NOT NULL,
    is_deleted boolean NOT NULL,
    reminder_sent_at timestamp with time zone
);


--
-- Name: evaluations_campaign_criteria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evaluations_campaign_criteria (
    id uuid NOT NULL,
    percentage numeric(5,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    campaign_id uuid NOT NULL,
    criteria_id uuid NOT NULL
);


--
-- Name: evaluations_criteria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evaluations_criteria (
    id uuid NOT NULL,
    name character varying(150) NOT NULL,
    description text,
    category character varying(30) NOT NULL,
    is_active boolean NOT NULL,
    version integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT evaluations_criteria_version_check CHECK ((version >= 0))
);


--
-- Name: evaluations_responses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evaluations_responses (
    id uuid NOT NULL,
    score smallint NOT NULL,
    comment text,
    created_at timestamp with time zone NOT NULL,
    criteria_id uuid NOT NULL,
    submission_id uuid NOT NULL,
    CONSTRAINT evaluations_responses_score_check CHECK ((score >= 0))
);


--
-- Name: evaluations_submissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evaluations_submissions (
    id uuid NOT NULL,
    status character varying(20) NOT NULL,
    global_score numeric(5,2) NOT NULL,
    submitted_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    campaign_id uuid NOT NULL,
    course_id uuid NOT NULL,
    student_id uuid NOT NULL,
    recommendation_score smallint,
    student_ref_hash character varying(64) NOT NULL,
    teacher_id uuid NOT NULL,
    CONSTRAINT evaluations_submissions_recommendation_score_check CHECK ((recommendation_score >= 0))
);


--
-- Name: evaluations_teacher_reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evaluations_teacher_reports (
    id uuid NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    department_id uuid,
    student_id uuid NOT NULL,
    teacher_id uuid NOT NULL
);


--
-- Name: evaluations_teacher_self_assessment_responses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evaluations_teacher_self_assessment_responses (
    id uuid NOT NULL,
    score smallint NOT NULL,
    assessment_id uuid CONSTRAINT evaluations_teacher_self_assessment_resp_assessment_id_not_null NOT NULL,
    criteria_id uuid CONSTRAINT evaluations_teacher_self_assessment_respon_criteria_id_not_null NOT NULL,
    CONSTRAINT evaluations_teacher_self_assessment_responses_score_check CHECK ((score >= 0))
);


--
-- Name: evaluations_teacher_self_assessments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evaluations_teacher_self_assessments (
    id uuid NOT NULL,
    submitted_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    semester_id uuid NOT NULL,
    teacher_id uuid NOT NULL
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id uuid NOT NULL,
    notif_type character varying(30) NOT NULL,
    channel character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    title character varying(200) NOT NULL,
    message text NOT NULL,
    related_resource character varying(100),
    related_resource_id character varying(100),
    sent_at timestamp with time zone,
    read_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    recipient_id uuid NOT NULL,
    payload jsonb NOT NULL,
    recipient_email character varying(254),
    recipient_phone character varying(30)
);


--
-- Name: report_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report_requests (
    id uuid NOT NULL,
    report_type character varying(30) NOT NULL,
    format character varying(10) NOT NULL,
    status character varying(20) NOT NULL,
    params jsonb NOT NULL,
    error text,
    created_at timestamp with time zone NOT NULL,
    done_at timestamp with time zone,
    requested_by_id uuid NOT NULL
);


--
-- Name: sync_academic_semesters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sync_academic_semesters (
    id uuid NOT NULL,
    name character varying(150) NOT NULL,
    academic_year character varying(20) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    is_active boolean NOT NULL,
    synced_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: sync_courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sync_courses (
    id uuid NOT NULL,
    university_id character varying(80) NOT NULL,
    code character varying(80) NOT NULL,
    name character varying(180) NOT NULL,
    description text,
    level character varying(50) NOT NULL,
    cohort character varying(80) NOT NULL,
    credit integer NOT NULL,
    is_active boolean NOT NULL,
    synced_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    semester_id uuid NOT NULL,
    department_id uuid NOT NULL,
    teacher_id uuid NOT NULL,
    grade_id uuid,
    CONSTRAINT sync_courses_credit_check CHECK ((credit >= 0))
);


--
-- Name: sync_courses_secondary_teachers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sync_courses_secondary_teachers (
    id bigint NOT NULL,
    coursesync_id uuid NOT NULL,
    teachersync_id uuid NOT NULL
);


--
-- Name: sync_courses_secondary_teachers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sync_courses_secondary_teachers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sync_courses_secondary_teachers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sync_departments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sync_departments (
    id uuid NOT NULL,
    code character varying(30) NOT NULL,
    name character varying(150) NOT NULL,
    description text,
    is_active boolean NOT NULL,
    synced_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: sync_grades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sync_grades (
    id uuid NOT NULL,
    synced_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    rank_order integer NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT sync_grades_rank_order_check CHECK ((rank_order >= 0))
);


--
-- Name: sync_import_batches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sync_import_batches (
    id uuid NOT NULL,
    entity_type character varying(20) NOT NULL,
    original_filename character varying(255) NOT NULL,
    status character varying(20) NOT NULL,
    headers jsonb NOT NULL,
    rows jsonb NOT NULL,
    mapping jsonb,
    validation jsonb,
    created_at timestamp with time zone NOT NULL,
    committed_at timestamp with time zone,
    created_by_id uuid
);


--
-- Name: sync_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sync_logs (
    id uuid NOT NULL,
    sync_type character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    teachers_count integer NOT NULL,
    students_count integer NOT NULL,
    courses_count integer NOT NULL,
    enrollments_count integer NOT NULL,
    message text,
    errors jsonb,
    started_at timestamp with time zone NOT NULL,
    ended_at timestamp with time zone,
    entity_type character varying(20),
    source_filename character varying(255),
    CONSTRAINT sync_logs_courses_count_check CHECK ((courses_count >= 0)),
    CONSTRAINT sync_logs_enrollments_count_check CHECK ((enrollments_count >= 0)),
    CONSTRAINT sync_logs_students_count_check CHECK ((students_count >= 0)),
    CONSTRAINT sync_logs_teachers_count_check CHECK ((teachers_count >= 0))
);


--
-- Name: sync_student_course_enrollments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sync_student_course_enrollments (
    id uuid NOT NULL,
    is_active boolean NOT NULL,
    enrolled_at timestamp with time zone NOT NULL,
    synced_at timestamp with time zone NOT NULL,
    course_id uuid NOT NULL,
    semester_id uuid NOT NULL,
    student_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: sync_students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sync_students (
    id uuid NOT NULL,
    university_id character varying(80) NOT NULL,
    student_code character varying(80) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(30),
    level character varying(50) NOT NULL,
    cohort character varying(80) NOT NULL,
    is_active boolean NOT NULL,
    synced_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    department_id uuid NOT NULL,
    academic_year character varying(20) NOT NULL
);


--
-- Name: sync_teachers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sync_teachers (
    id uuid NOT NULL,
    university_id character varying(80) NOT NULL,
    matricule character varying(80) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(30),
    specialty character varying(150),
    is_active boolean NOT NULL,
    synced_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    department_id uuid NOT NULL,
    grade_id uuid
);


--
-- Name: ai_bias_detection_results ai_bias_detection_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_bias_detection_results
    ADD CONSTRAINT ai_bias_detection_results_pkey PRIMARY KEY (id);


--
-- Name: ai_clustering_results ai_clustering_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_clustering_results
    ADD CONSTRAINT ai_clustering_results_pkey PRIMARY KEY (id);


--
-- Name: ai_evaluator_bias_config ai_evaluator_bias_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_evaluator_bias_config
    ADD CONSTRAINT ai_evaluator_bias_config_pkey PRIMARY KEY (id);


--
-- Name: ai_evaluator_bias_results ai_evaluator_bias_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_evaluator_bias_results
    ADD CONSTRAINT ai_evaluator_bias_results_pkey PRIMARY KEY (id);


--
-- Name: ai_teacher_score_predictions ai_teacher_score_predictions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_teacher_score_predictions
    ADD CONSTRAINT ai_teacher_score_predictions_pkey PRIMARY KEY (id);


--
-- Name: ai_training_catalog ai_training_catalog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_training_catalog
    ADD CONSTRAINT ai_training_catalog_pkey PRIMARY KEY (id);


--
-- Name: analytics_classification_config analytics_classification_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analytics_classification_config
    ADD CONSTRAINT analytics_classification_config_pkey PRIMARY KEY (id);


--
-- Name: attendance_alerts attendance_alerts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_alerts
    ADD CONSTRAINT attendance_alerts_pkey PRIMARY KEY (id);


--
-- Name: attendance_records attendance_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_records
    ADD CONSTRAINT attendance_records_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: auth_users auth_users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_users
    ADD CONSTRAINT auth_users_email_key UNIQUE (email);


--
-- Name: auth_users auth_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_users
    ADD CONSTRAINT auth_users_pkey PRIMARY KEY (id);


--
-- Name: auth_users auth_users_student_profile_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_users
    ADD CONSTRAINT auth_users_student_profile_id_key UNIQUE (student_profile_id);


--
-- Name: auth_users auth_users_teacher_profile_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_users
    ADD CONSTRAINT auth_users_teacher_profile_id_key UNIQUE (teacher_profile_id);


--
-- Name: campaigns_evaluation_campaigns campaigns_evaluation_campaigns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaigns_evaluation_campaigns
    ADD CONSTRAINT campaigns_evaluation_campaigns_pkey PRIMARY KEY (id);


--
-- Name: evaluations_campaign_criteria evaluations_campaign_cri_campaign_id_criteria_id_84434cfb_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_campaign_criteria
    ADD CONSTRAINT evaluations_campaign_cri_campaign_id_criteria_id_84434cfb_uniq UNIQUE (campaign_id, criteria_id);


--
-- Name: evaluations_campaign_criteria evaluations_campaign_criteria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_campaign_criteria
    ADD CONSTRAINT evaluations_campaign_criteria_pkey PRIMARY KEY (id);


--
-- Name: evaluations_criteria evaluations_criteria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_criteria
    ADD CONSTRAINT evaluations_criteria_pkey PRIMARY KEY (id);


--
-- Name: evaluations_responses evaluations_responses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_responses
    ADD CONSTRAINT evaluations_responses_pkey PRIMARY KEY (id);


--
-- Name: evaluations_responses evaluations_responses_submission_id_criteria_id_61454fba_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_responses
    ADD CONSTRAINT evaluations_responses_submission_id_criteria_id_61454fba_uniq UNIQUE (submission_id, criteria_id);


--
-- Name: evaluations_submissions evaluations_submissions_campaign_id_course_id_st_17e4e9f3_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_submissions
    ADD CONSTRAINT evaluations_submissions_campaign_id_course_id_st_17e4e9f3_uniq UNIQUE (campaign_id, course_id, student_id, teacher_id);


--
-- Name: evaluations_submissions evaluations_submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_submissions
    ADD CONSTRAINT evaluations_submissions_pkey PRIMARY KEY (id);


--
-- Name: evaluations_teacher_reports evaluations_teacher_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_teacher_reports
    ADD CONSTRAINT evaluations_teacher_reports_pkey PRIMARY KEY (id);


--
-- Name: evaluations_teacher_self_assessment_responses evaluations_teacher_self_assessment_id_criteria_i_eb106402_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_teacher_self_assessment_responses
    ADD CONSTRAINT evaluations_teacher_self_assessment_id_criteria_i_eb106402_uniq UNIQUE (assessment_id, criteria_id);


--
-- Name: evaluations_teacher_self_assessment_responses evaluations_teacher_self_assessment_responses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_teacher_self_assessment_responses
    ADD CONSTRAINT evaluations_teacher_self_assessment_responses_pkey PRIMARY KEY (id);


--
-- Name: evaluations_teacher_self_assessments evaluations_teacher_self_assessments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_teacher_self_assessments
    ADD CONSTRAINT evaluations_teacher_self_assessments_pkey PRIMARY KEY (id);


--
-- Name: evaluations_teacher_self_assessments evaluations_teacher_self_teacher_id_semester_id_6166324d_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_teacher_self_assessments
    ADD CONSTRAINT evaluations_teacher_self_teacher_id_semester_id_6166324d_uniq UNIQUE (teacher_id, semester_id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: report_requests report_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_requests
    ADD CONSTRAINT report_requests_pkey PRIMARY KEY (id);


--
-- Name: sync_academic_semesters sync_academic_semesters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_academic_semesters
    ADD CONSTRAINT sync_academic_semesters_pkey PRIMARY KEY (id);


--
-- Name: sync_courses sync_courses_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_courses
    ADD CONSTRAINT sync_courses_code_key UNIQUE (code);


--
-- Name: sync_courses sync_courses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_courses
    ADD CONSTRAINT sync_courses_pkey PRIMARY KEY (id);


--
-- Name: sync_courses_secondary_teachers sync_courses_secondary_t_coursesync_id_teachersyn_48a0c4d1_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_courses_secondary_teachers
    ADD CONSTRAINT sync_courses_secondary_t_coursesync_id_teachersyn_48a0c4d1_uniq UNIQUE (coursesync_id, teachersync_id);


--
-- Name: sync_courses_secondary_teachers sync_courses_secondary_teachers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_courses_secondary_teachers
    ADD CONSTRAINT sync_courses_secondary_teachers_pkey PRIMARY KEY (id);


--
-- Name: sync_courses sync_courses_university_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_courses
    ADD CONSTRAINT sync_courses_university_id_key UNIQUE (university_id);


--
-- Name: sync_departments sync_departments_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_departments
    ADD CONSTRAINT sync_departments_code_key UNIQUE (code);


--
-- Name: sync_departments sync_departments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_departments
    ADD CONSTRAINT sync_departments_pkey PRIMARY KEY (id);


--
-- Name: sync_grades sync_grades_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_grades
    ADD CONSTRAINT sync_grades_name_key UNIQUE (name);


--
-- Name: sync_grades sync_grades_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_grades
    ADD CONSTRAINT sync_grades_pkey PRIMARY KEY (id);


--
-- Name: sync_import_batches sync_import_batches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_import_batches
    ADD CONSTRAINT sync_import_batches_pkey PRIMARY KEY (id);


--
-- Name: sync_logs sync_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_logs
    ADD CONSTRAINT sync_logs_pkey PRIMARY KEY (id);


--
-- Name: sync_student_course_enrollments sync_student_course_enro_student_id_course_id_sem_7855dff1_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_student_course_enrollments
    ADD CONSTRAINT sync_student_course_enro_student_id_course_id_sem_7855dff1_uniq UNIQUE (student_id, course_id, semester_id);


--
-- Name: sync_student_course_enrollments sync_student_course_enrollments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_student_course_enrollments
    ADD CONSTRAINT sync_student_course_enrollments_pkey PRIMARY KEY (id);


--
-- Name: sync_students sync_students_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_students
    ADD CONSTRAINT sync_students_email_key UNIQUE (email);


--
-- Name: sync_students sync_students_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_students
    ADD CONSTRAINT sync_students_pkey PRIMARY KEY (id);


--
-- Name: sync_students sync_students_student_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_students
    ADD CONSTRAINT sync_students_student_code_key UNIQUE (student_code);


--
-- Name: sync_students sync_students_university_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_students
    ADD CONSTRAINT sync_students_university_id_key UNIQUE (university_id);


--
-- Name: sync_teachers sync_teachers_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_teachers
    ADD CONSTRAINT sync_teachers_email_key UNIQUE (email);


--
-- Name: sync_teachers sync_teachers_matricule_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_teachers
    ADD CONSTRAINT sync_teachers_matricule_key UNIQUE (matricule);


--
-- Name: sync_teachers sync_teachers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_teachers
    ADD CONSTRAINT sync_teachers_pkey PRIMARY KEY (id);


--
-- Name: sync_teachers sync_teachers_university_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_teachers
    ADD CONSTRAINT sync_teachers_university_id_key UNIQUE (university_id);


--
-- Name: ai_teacher__teacher_bd7fd6_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ai_teacher__teacher_bd7fd6_idx ON public.ai_teacher_score_predictions USING btree (teacher_id, computed_at DESC);


--
-- Name: ai_teacher_score_predictions_teacher_id_b2167a2b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ai_teacher_score_predictions_teacher_id_b2167a2b ON public.ai_teacher_score_predictions USING btree (teacher_id);


--
-- Name: attendance__course__9f4748_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX attendance__course__9f4748_idx ON public.attendance_records USING btree (course_id);


--
-- Name: attendance__period_0752ca_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX attendance__period_0752ca_idx ON public.attendance_alerts USING btree (period);


--
-- Name: attendance__schedul_13dcb5_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX attendance__schedul_13dcb5_idx ON public.attendance_records USING btree (scheduled_at);


--
-- Name: attendance__status_5b1243_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX attendance__status_5b1243_idx ON public.attendance_records USING btree (status);


--
-- Name: attendance__status_f47f8d_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX attendance__status_f47f8d_idx ON public.attendance_alerts USING btree (status);


--
-- Name: attendance__teacher_2e0f09_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX attendance__teacher_2e0f09_idx ON public.attendance_records USING btree (teacher_id);


--
-- Name: attendance__teacher_f1edd0_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX attendance__teacher_f1edd0_idx ON public.attendance_alerts USING btree (teacher_id);


--
-- Name: attendance_alerts_teacher_id_8004d7e6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX attendance_alerts_teacher_id_8004d7e6 ON public.attendance_alerts USING btree (teacher_id);


--
-- Name: attendance_records_course_id_c2d179a0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX attendance_records_course_id_c2d179a0 ON public.attendance_records USING btree (course_id);


--
-- Name: attendance_records_teacher_id_1e38925b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX attendance_records_teacher_id_1e38925b ON public.attendance_records USING btree (teacher_id);


--
-- Name: audit_logs_action_31f574_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_logs_action_31f574_idx ON public.audit_logs USING btree (action);


--
-- Name: audit_logs_resourc_41dc7e_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_logs_resourc_41dc7e_idx ON public.audit_logs USING btree (resource);


--
-- Name: audit_logs_timesta_423be6_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_logs_timesta_423be6_idx ON public.audit_logs USING btree ("timestamp");


--
-- Name: audit_logs_user_id_73c422_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_logs_user_id_73c422_idx ON public.audit_logs USING btree (user_id);


--
-- Name: audit_logs_user_id_752b0e2b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_logs_user_id_752b0e2b ON public.audit_logs USING btree (user_id);


--
-- Name: auth_users_email_d961f1be_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_users_email_d961f1be_like ON public.auth_users USING btree (email varchar_pattern_ops);


--
-- Name: campaigns_e_is_dele_717e63_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX campaigns_e_is_dele_717e63_idx ON public.campaigns_evaluation_campaigns USING btree (is_deleted);


--
-- Name: campaigns_e_semeste_a3108b_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX campaigns_e_semeste_a3108b_idx ON public.campaigns_evaluation_campaigns USING btree (semester_id);


--
-- Name: campaigns_e_start_d_5a7e84_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX campaigns_e_start_d_5a7e84_idx ON public.campaigns_evaluation_campaigns USING btree (start_date, end_date);


--
-- Name: campaigns_e_status_f31de7_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX campaigns_e_status_f31de7_idx ON public.campaigns_evaluation_campaigns USING btree (status);


--
-- Name: campaigns_evaluation_campaigns_created_by_id_d04faf99; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX campaigns_evaluation_campaigns_created_by_id_d04faf99 ON public.campaigns_evaluation_campaigns USING btree (created_by_id);


--
-- Name: campaigns_evaluation_campaigns_semester_id_d5c6b1bc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX campaigns_evaluation_campaigns_semester_id_d5c6b1bc ON public.campaigns_evaluation_campaigns USING btree (semester_id);


--
-- Name: evaluations_campaig_02beb5_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_campaig_02beb5_idx ON public.evaluations_submissions USING btree (campaign_id);


--
-- Name: evaluations_campaign_criteria_campaign_id_5069a731; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_campaign_criteria_campaign_id_5069a731 ON public.evaluations_campaign_criteria USING btree (campaign_id);


--
-- Name: evaluations_campaign_criteria_criteria_id_0f766ee3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_campaign_criteria_criteria_id_0f766ee3 ON public.evaluations_campaign_criteria USING btree (criteria_id);


--
-- Name: evaluations_categor_d6f497_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_categor_d6f497_idx ON public.evaluations_criteria USING btree (category);


--
-- Name: evaluations_course__594a2e_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_course__594a2e_idx ON public.evaluations_submissions USING btree (course_id);


--
-- Name: evaluations_criteri_892cc5_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_criteri_892cc5_idx ON public.evaluations_responses USING btree (criteria_id);


--
-- Name: evaluations_is_acti_dd5341_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_is_acti_dd5341_idx ON public.evaluations_criteria USING btree (is_active);


--
-- Name: evaluations_responses_criteria_id_38868565; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_responses_criteria_id_38868565 ON public.evaluations_responses USING btree (criteria_id);


--
-- Name: evaluations_responses_submission_id_e2bb7e45; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_responses_submission_id_e2bb7e45 ON public.evaluations_responses USING btree (submission_id);


--
-- Name: evaluations_status_322fd6_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_status_322fd6_idx ON public.evaluations_submissions USING btree (status);


--
-- Name: evaluations_student_229db2_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_student_229db2_idx ON public.evaluations_submissions USING btree (student_id);


--
-- Name: evaluations_student_d54546_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_student_d54546_idx ON public.evaluations_teacher_reports USING btree (student_id);


--
-- Name: evaluations_submiss_4adcec_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_submiss_4adcec_idx ON public.evaluations_responses USING btree (submission_id);


--
-- Name: evaluations_submissions_campaign_id_465a1cee; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_submissions_campaign_id_465a1cee ON public.evaluations_submissions USING btree (campaign_id);


--
-- Name: evaluations_submissions_course_id_0f602180; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_submissions_course_id_0f602180 ON public.evaluations_submissions USING btree (course_id);


--
-- Name: evaluations_submissions_student_id_eff7b6df; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_submissions_student_id_eff7b6df ON public.evaluations_submissions USING btree (student_id);


--
-- Name: evaluations_submissions_teacher_id_0d687df2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_submissions_teacher_id_0d687df2 ON public.evaluations_submissions USING btree (teacher_id);


--
-- Name: evaluations_teacher_3aaf0e_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_teacher_3aaf0e_idx ON public.evaluations_submissions USING btree (teacher_id);


--
-- Name: evaluations_teacher_70b6e0_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_teacher_70b6e0_idx ON public.evaluations_teacher_reports USING btree (teacher_id);


--
-- Name: evaluations_teacher_reports_department_id_b6660952; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_teacher_reports_department_id_b6660952 ON public.evaluations_teacher_reports USING btree (department_id);


--
-- Name: evaluations_teacher_reports_student_id_45fc9995; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_teacher_reports_student_id_45fc9995 ON public.evaluations_teacher_reports USING btree (student_id);


--
-- Name: evaluations_teacher_reports_teacher_id_98e978b1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_teacher_reports_teacher_id_98e978b1 ON public.evaluations_teacher_reports USING btree (teacher_id);


--
-- Name: evaluations_teacher_self_a_assessment_id_e0134a04; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_teacher_self_a_assessment_id_e0134a04 ON public.evaluations_teacher_self_assessment_responses USING btree (assessment_id);


--
-- Name: evaluations_teacher_self_a_criteria_id_7acded96; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_teacher_self_a_criteria_id_7acded96 ON public.evaluations_teacher_self_assessment_responses USING btree (criteria_id);


--
-- Name: evaluations_teacher_self_assessments_semester_id_c3789a9c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_teacher_self_assessments_semester_id_c3789a9c ON public.evaluations_teacher_self_assessments USING btree (semester_id);


--
-- Name: evaluations_teacher_self_assessments_teacher_id_ea428696; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX evaluations_teacher_self_assessments_teacher_id_ea428696 ON public.evaluations_teacher_self_assessments USING btree (teacher_id);


--
-- Name: notificatio_channel_d2a579_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notificatio_channel_d2a579_idx ON public.notifications USING btree (channel);


--
-- Name: notificatio_notif_t_d57951_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notificatio_notif_t_d57951_idx ON public.notifications USING btree (notif_type);


--
-- Name: notificatio_recipie_1dd18d_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notificatio_recipie_1dd18d_idx ON public.notifications USING btree (recipient_id);


--
-- Name: notificatio_status_fce6f5_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notificatio_status_fce6f5_idx ON public.notifications USING btree (status);


--
-- Name: notifications_recipient_id_e1133bac; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notifications_recipient_id_e1133bac ON public.notifications USING btree (recipient_id);


--
-- Name: report_requests_requested_by_id_8951b641; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX report_requests_requested_by_id_8951b641 ON public.report_requests USING btree (requested_by_id);


--
-- Name: sync_course_code_d9eedf_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_course_code_d9eedf_idx ON public.sync_courses USING btree (code);


--
-- Name: sync_course_departm_3324af_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_course_departm_3324af_idx ON public.sync_courses USING btree (department_id);


--
-- Name: sync_course_semeste_432b70_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_course_semeste_432b70_idx ON public.sync_courses USING btree (semester_id);


--
-- Name: sync_course_teacher_82e635_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_course_teacher_82e635_idx ON public.sync_courses USING btree (teacher_id);


--
-- Name: sync_course_univers_617022_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_course_univers_617022_idx ON public.sync_courses USING btree (university_id);


--
-- Name: sync_courses_code_e96c2239_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_courses_code_e96c2239_like ON public.sync_courses USING btree (code varchar_pattern_ops);


--
-- Name: sync_courses_department_id_714efc51; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_courses_department_id_714efc51 ON public.sync_courses USING btree (department_id);


--
-- Name: sync_courses_grade_id_36b3bf9e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_courses_grade_id_36b3bf9e ON public.sync_courses USING btree (grade_id);


--
-- Name: sync_courses_secondary_teachers_coursesync_id_23f31694; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_courses_secondary_teachers_coursesync_id_23f31694 ON public.sync_courses_secondary_teachers USING btree (coursesync_id);


--
-- Name: sync_courses_secondary_teachers_teachersync_id_fea8ac55; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_courses_secondary_teachers_teachersync_id_fea8ac55 ON public.sync_courses_secondary_teachers USING btree (teachersync_id);


--
-- Name: sync_courses_semester_id_4b968fe2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_courses_semester_id_4b968fe2 ON public.sync_courses USING btree (semester_id);


--
-- Name: sync_courses_teacher_id_b9c0ee68; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_courses_teacher_id_b9c0ee68 ON public.sync_courses USING btree (teacher_id);


--
-- Name: sync_courses_university_id_a1b116e7_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_courses_university_id_a1b116e7_like ON public.sync_courses USING btree (university_id varchar_pattern_ops);


--
-- Name: sync_departments_code_982a4889_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_departments_code_982a4889_like ON public.sync_departments USING btree (code varchar_pattern_ops);


--
-- Name: sync_grades_name_1832cb58_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_grades_name_1832cb58_like ON public.sync_grades USING btree (name varchar_pattern_ops);


--
-- Name: sync_import_batches_created_by_id_6e3e3529; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_import_batches_created_by_id_6e3e3529 ON public.sync_import_batches USING btree (created_by_id);


--
-- Name: sync_studen_course__2f5558_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_studen_course__2f5558_idx ON public.sync_student_course_enrollments USING btree (course_id);


--
-- Name: sync_studen_email_f89661_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_studen_email_f89661_idx ON public.sync_students USING btree (email);


--
-- Name: sync_studen_level_a0b4bc_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_studen_level_a0b4bc_idx ON public.sync_students USING btree (level, cohort);


--
-- Name: sync_studen_semeste_b6b34c_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_studen_semeste_b6b34c_idx ON public.sync_student_course_enrollments USING btree (semester_id);


--
-- Name: sync_studen_student_949ff5_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_studen_student_949ff5_idx ON public.sync_students USING btree (student_code);


--
-- Name: sync_studen_student_e3b675_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_studen_student_e3b675_idx ON public.sync_student_course_enrollments USING btree (student_id);


--
-- Name: sync_studen_univers_e7604d_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_studen_univers_e7604d_idx ON public.sync_students USING btree (university_id);


--
-- Name: sync_student_course_enrollments_course_id_4dfa84d6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_student_course_enrollments_course_id_4dfa84d6 ON public.sync_student_course_enrollments USING btree (course_id);


--
-- Name: sync_student_course_enrollments_semester_id_915cf41b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_student_course_enrollments_semester_id_915cf41b ON public.sync_student_course_enrollments USING btree (semester_id);


--
-- Name: sync_student_course_enrollments_student_id_483a745b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_student_course_enrollments_student_id_483a745b ON public.sync_student_course_enrollments USING btree (student_id);


--
-- Name: sync_students_department_id_a7b08325; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_students_department_id_a7b08325 ON public.sync_students USING btree (department_id);


--
-- Name: sync_students_email_eed2262b_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_students_email_eed2262b_like ON public.sync_students USING btree (email varchar_pattern_ops);


--
-- Name: sync_students_student_code_c1c8652e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_students_student_code_c1c8652e_like ON public.sync_students USING btree (student_code varchar_pattern_ops);


--
-- Name: sync_students_university_id_792ccf56_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_students_university_id_792ccf56_like ON public.sync_students USING btree (university_id varchar_pattern_ops);


--
-- Name: sync_teache_email_7035d1_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_teache_email_7035d1_idx ON public.sync_teachers USING btree (email);


--
-- Name: sync_teache_matricu_ef21cf_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_teache_matricu_ef21cf_idx ON public.sync_teachers USING btree (matricule);


--
-- Name: sync_teache_univers_c174a8_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_teache_univers_c174a8_idx ON public.sync_teachers USING btree (university_id);


--
-- Name: sync_teachers_department_id_8b530baf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_teachers_department_id_8b530baf ON public.sync_teachers USING btree (department_id);


--
-- Name: sync_teachers_email_5605b1b0_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_teachers_email_5605b1b0_like ON public.sync_teachers USING btree (email varchar_pattern_ops);


--
-- Name: sync_teachers_grade_fk_id_6fdea016; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_teachers_grade_fk_id_6fdea016 ON public.sync_teachers USING btree (grade_id);


--
-- Name: sync_teachers_matricule_2d54fec8_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_teachers_matricule_2d54fec8_like ON public.sync_teachers USING btree (matricule varchar_pattern_ops);


--
-- Name: sync_teachers_university_id_c5ae2a92_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_teachers_university_id_c5ae2a92_like ON public.sync_teachers USING btree (university_id varchar_pattern_ops);


--
-- Name: ai_teacher_score_predictions ai_teacher_score_pre_teacher_id_b2167a2b_fk_sync_teac; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_teacher_score_predictions
    ADD CONSTRAINT ai_teacher_score_pre_teacher_id_b2167a2b_fk_sync_teac FOREIGN KEY (teacher_id) REFERENCES public.sync_teachers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: attendance_alerts attendance_alerts_teacher_id_8004d7e6_fk_sync_teachers_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_alerts
    ADD CONSTRAINT attendance_alerts_teacher_id_8004d7e6_fk_sync_teachers_id FOREIGN KEY (teacher_id) REFERENCES public.sync_teachers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: attendance_records attendance_records_course_id_c2d179a0_fk_sync_courses_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_records
    ADD CONSTRAINT attendance_records_course_id_c2d179a0_fk_sync_courses_id FOREIGN KEY (course_id) REFERENCES public.sync_courses(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: attendance_records attendance_records_teacher_id_1e38925b_fk_sync_teachers_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_records
    ADD CONSTRAINT attendance_records_teacher_id_1e38925b_fk_sync_teachers_id FOREIGN KEY (teacher_id) REFERENCES public.sync_teachers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: audit_logs audit_logs_user_id_752b0e2b_fk_auth_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_user_id_752b0e2b_fk_auth_users_id FOREIGN KEY (user_id) REFERENCES public.auth_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_users auth_users_student_profile_id_2ed15239_fk_sync_students_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_users
    ADD CONSTRAINT auth_users_student_profile_id_2ed15239_fk_sync_students_id FOREIGN KEY (student_profile_id) REFERENCES public.sync_students(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_users auth_users_teacher_profile_id_8198577a_fk_sync_teachers_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_users
    ADD CONSTRAINT auth_users_teacher_profile_id_8198577a_fk_sync_teachers_id FOREIGN KEY (teacher_profile_id) REFERENCES public.sync_teachers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: campaigns_evaluation_campaigns campaigns_evaluation_created_by_id_d04faf99_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaigns_evaluation_campaigns
    ADD CONSTRAINT campaigns_evaluation_created_by_id_d04faf99_fk_auth_user FOREIGN KEY (created_by_id) REFERENCES public.auth_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: campaigns_evaluation_campaigns campaigns_evaluation_semester_id_d5c6b1bc_fk_sync_acad; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaigns_evaluation_campaigns
    ADD CONSTRAINT campaigns_evaluation_semester_id_d5c6b1bc_fk_sync_acad FOREIGN KEY (semester_id) REFERENCES public.sync_academic_semesters(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluations_campaign_criteria evaluations_campaign_campaign_id_5069a731_fk_campaigns; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_campaign_criteria
    ADD CONSTRAINT evaluations_campaign_campaign_id_5069a731_fk_campaigns FOREIGN KEY (campaign_id) REFERENCES public.campaigns_evaluation_campaigns(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluations_campaign_criteria evaluations_campaign_criteria_id_0f766ee3_fk_evaluatio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_campaign_criteria
    ADD CONSTRAINT evaluations_campaign_criteria_id_0f766ee3_fk_evaluatio FOREIGN KEY (criteria_id) REFERENCES public.evaluations_criteria(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluations_responses evaluations_response_criteria_id_38868565_fk_evaluatio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_responses
    ADD CONSTRAINT evaluations_response_criteria_id_38868565_fk_evaluatio FOREIGN KEY (criteria_id) REFERENCES public.evaluations_criteria(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluations_responses evaluations_response_submission_id_e2bb7e45_fk_evaluatio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_responses
    ADD CONSTRAINT evaluations_response_submission_id_e2bb7e45_fk_evaluatio FOREIGN KEY (submission_id) REFERENCES public.evaluations_submissions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluations_submissions evaluations_submissi_campaign_id_465a1cee_fk_campaigns; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_submissions
    ADD CONSTRAINT evaluations_submissi_campaign_id_465a1cee_fk_campaigns FOREIGN KEY (campaign_id) REFERENCES public.campaigns_evaluation_campaigns(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluations_submissions evaluations_submissions_course_id_0f602180_fk_sync_courses_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_submissions
    ADD CONSTRAINT evaluations_submissions_course_id_0f602180_fk_sync_courses_id FOREIGN KEY (course_id) REFERENCES public.sync_courses(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluations_submissions evaluations_submissions_student_id_eff7b6df_fk_auth_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_submissions
    ADD CONSTRAINT evaluations_submissions_student_id_eff7b6df_fk_auth_users_id FOREIGN KEY (student_id) REFERENCES public.auth_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluations_submissions evaluations_submissions_teacher_id_0d687df2_fk_sync_teachers_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_submissions
    ADD CONSTRAINT evaluations_submissions_teacher_id_0d687df2_fk_sync_teachers_id FOREIGN KEY (teacher_id) REFERENCES public.sync_teachers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluations_teacher_self_assessment_responses evaluations_teacher__assessment_id_e0134a04_fk_evaluatio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_teacher_self_assessment_responses
    ADD CONSTRAINT evaluations_teacher__assessment_id_e0134a04_fk_evaluatio FOREIGN KEY (assessment_id) REFERENCES public.evaluations_teacher_self_assessments(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluations_teacher_self_assessment_responses evaluations_teacher__criteria_id_7acded96_fk_evaluatio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_teacher_self_assessment_responses
    ADD CONSTRAINT evaluations_teacher__criteria_id_7acded96_fk_evaluatio FOREIGN KEY (criteria_id) REFERENCES public.evaluations_criteria(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluations_teacher_reports evaluations_teacher__department_id_b6660952_fk_sync_depa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_teacher_reports
    ADD CONSTRAINT evaluations_teacher__department_id_b6660952_fk_sync_depa FOREIGN KEY (department_id) REFERENCES public.sync_departments(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluations_teacher_self_assessments evaluations_teacher__semester_id_c3789a9c_fk_sync_acad; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_teacher_self_assessments
    ADD CONSTRAINT evaluations_teacher__semester_id_c3789a9c_fk_sync_acad FOREIGN KEY (semester_id) REFERENCES public.sync_academic_semesters(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluations_teacher_reports evaluations_teacher__student_id_45fc9995_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_teacher_reports
    ADD CONSTRAINT evaluations_teacher__student_id_45fc9995_fk_auth_user FOREIGN KEY (student_id) REFERENCES public.auth_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluations_teacher_reports evaluations_teacher__teacher_id_98e978b1_fk_sync_teac; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_teacher_reports
    ADD CONSTRAINT evaluations_teacher__teacher_id_98e978b1_fk_sync_teac FOREIGN KEY (teacher_id) REFERENCES public.sync_teachers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluations_teacher_self_assessments evaluations_teacher__teacher_id_ea428696_fk_sync_teac; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluations_teacher_self_assessments
    ADD CONSTRAINT evaluations_teacher__teacher_id_ea428696_fk_sync_teac FOREIGN KEY (teacher_id) REFERENCES public.sync_teachers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications notifications_recipient_id_e1133bac_fk_auth_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_recipient_id_e1133bac_fk_auth_users_id FOREIGN KEY (recipient_id) REFERENCES public.auth_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: report_requests report_requests_requested_by_id_8951b641_fk_auth_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_requests
    ADD CONSTRAINT report_requests_requested_by_id_8951b641_fk_auth_users_id FOREIGN KEY (requested_by_id) REFERENCES public.auth_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sync_courses sync_courses_department_id_714efc51_fk_sync_departments_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_courses
    ADD CONSTRAINT sync_courses_department_id_714efc51_fk_sync_departments_id FOREIGN KEY (department_id) REFERENCES public.sync_departments(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sync_courses sync_courses_grade_id_36b3bf9e_fk_sync_grades_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_courses
    ADD CONSTRAINT sync_courses_grade_id_36b3bf9e_fk_sync_grades_id FOREIGN KEY (grade_id) REFERENCES public.sync_grades(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sync_courses_secondary_teachers sync_courses_seconda_coursesync_id_23f31694_fk_sync_cour; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_courses_secondary_teachers
    ADD CONSTRAINT sync_courses_seconda_coursesync_id_23f31694_fk_sync_cour FOREIGN KEY (coursesync_id) REFERENCES public.sync_courses(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sync_courses_secondary_teachers sync_courses_seconda_teachersync_id_fea8ac55_fk_sync_teac; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_courses_secondary_teachers
    ADD CONSTRAINT sync_courses_seconda_teachersync_id_fea8ac55_fk_sync_teac FOREIGN KEY (teachersync_id) REFERENCES public.sync_teachers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sync_courses sync_courses_semester_id_4b968fe2_fk_sync_academic_semesters_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_courses
    ADD CONSTRAINT sync_courses_semester_id_4b968fe2_fk_sync_academic_semesters_id FOREIGN KEY (semester_id) REFERENCES public.sync_academic_semesters(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sync_courses sync_courses_teacher_id_b9c0ee68_fk_sync_teachers_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_courses
    ADD CONSTRAINT sync_courses_teacher_id_b9c0ee68_fk_sync_teachers_id FOREIGN KEY (teacher_id) REFERENCES public.sync_teachers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sync_import_batches sync_import_batches_created_by_id_6e3e3529_fk_auth_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_import_batches
    ADD CONSTRAINT sync_import_batches_created_by_id_6e3e3529_fk_auth_users_id FOREIGN KEY (created_by_id) REFERENCES public.auth_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sync_student_course_enrollments sync_student_course__course_id_4dfa84d6_fk_sync_cour; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_student_course_enrollments
    ADD CONSTRAINT sync_student_course__course_id_4dfa84d6_fk_sync_cour FOREIGN KEY (course_id) REFERENCES public.sync_courses(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sync_student_course_enrollments sync_student_course__semester_id_915cf41b_fk_sync_acad; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_student_course_enrollments
    ADD CONSTRAINT sync_student_course__semester_id_915cf41b_fk_sync_acad FOREIGN KEY (semester_id) REFERENCES public.sync_academic_semesters(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sync_student_course_enrollments sync_student_course__student_id_483a745b_fk_sync_stud; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_student_course_enrollments
    ADD CONSTRAINT sync_student_course__student_id_483a745b_fk_sync_stud FOREIGN KEY (student_id) REFERENCES public.sync_students(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sync_students sync_students_department_id_a7b08325_fk_sync_departments_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_students
    ADD CONSTRAINT sync_students_department_id_a7b08325_fk_sync_departments_id FOREIGN KEY (department_id) REFERENCES public.sync_departments(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sync_teachers sync_teachers_department_id_8b530baf_fk_sync_departments_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_teachers
    ADD CONSTRAINT sync_teachers_department_id_8b530baf_fk_sync_departments_id FOREIGN KEY (department_id) REFERENCES public.sync_departments(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sync_teachers sync_teachers_grade_id_6793fc58_fk_sync_grades_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_teachers
    ADD CONSTRAINT sync_teachers_grade_id_6793fc58_fk_sync_grades_id FOREIGN KEY (grade_id) REFERENCES public.sync_grades(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--
